import { type RouteConfig, index, route } from "@react-router/dev/routes";

export default [
  index("routes/index.tsx"),
  route("home", "routes/home.tsx"),
  route("shop", "routes/shop.tsx"),
  route("products/:productId", "routes/product-detail.tsx"),
  route("contact-us", "routes/contact-us.tsx"),
  route("shipping-info", "routes/shipping-info.tsx"),
  route("gallery", "routes/gallery.tsx"),
  route("about-us", "routes/about-us.tsx"),
  route("compare-products", "routes/compare-products.tsx"),
  route("collections", "routes/collections.tsx"),
  route("cart", "routes/cart.tsx"),
  route("checkout/create-session", "routes/checkout.create-session.tsx"),
  route("checkout/success", "routes/checkout.success.tsx"),
  route("checkout/cancel", "routes/checkout.cancel.tsx"),
  route("stripe/webhook", "routes/stripe.webhook.tsx"),
  route("add-product", "routes/add-product.tsx"),
  route("archive", "routes/archive.tsx"),
  route("edit-home", "routes/edit-home.tsx"),
  route("login", "routes/login.tsx"),
  route("register", "routes/register.tsx"),
  route("account", "routes/account.tsx"),
  route("admin", "routes/admin.tsx"),
  route("unauthorized", "routes/unauthorized.tsx"),
] satisfies RouteConfig;
